version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: wemake-python-styleguide
    versions:
    - 0.15.1
  - dependency-name: django
    versions:
    - 3.1.6
- package-ecosystem: pip
  directory: "/docs"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
