language: python

sudo: false

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO="Django>=1.5.0,<1.6.0"
  - DJANGO="Django>=1.6.0,<1.7.0"
  - DJANGO="Django>=1.7.0,<1.8.0"
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django==1.9rc1"

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=1.6.0,<1.7.0"

cache:
  directories:
    - $HOME/.pip-cache/

install:
  - pip install --upgrade pip
  - pip install -e . --cache-dir $HOME/.pip-cache
  - pip install nose pep8 --cache-dir $HOME/.pip-cache
  - travis_retry pip install $DJANGO --cache-dir $HOME/.pip-cache

script:
  - export DJANGO_SETTINGS_MODULE=example.settings
  - cd example && nosetests
