language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install tox-travis wheel

script:
  - tox

after_success:
  - coveralls

deploy:
  provider: pypi
  user: sobolevn
  password: $PYPI_PASSWORD  # password is hidden
  distributions: sdist bdist_wheel
  on:
    branch: master  # only in master branch
    tags: true  # deploy on tags only

notifications:
  email:
    on_success: never
    on_failure: change
