language: python

python:
  - 3.5  # fix for the "`python3.5` is not found"

env:
  - TOX_ENV=py27-dj15
  - TOX_ENV=py27-dj16
  - TOX_ENV=py27-dj17
  - TOX_ENV=py27-dj18
  - TOX_ENV=py27-dj19
  - TOX_ENV=py27-dj110
  - TOX_ENV=py34-dj16
  - TOX_ENV=py34-dj17
  - TOX_ENV=py34-dj18
  - TOX_ENV=py34-dj19
  - TOX_ENV=py34-dj110
  - TOX_ENV=py35-dj18
  - TOX_ENV=py35-dj19
  - TOX_ENV=py35-dj110
  - TOX_ENV=lint
  - TOX_ENV=cover

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls

deploy:
  provider: pypi
  user: sobolevn
  password: $PYPI_PASSWORD  # password is hidden
  on:
    branch: master  # only in master branch
    tags: true  # deploy on tags only
    condition: "${TOX_ENV} == 'cover'"  # deploy only once

notifications:
  email:
    on_success: never
    on_failure: change
